### ISSUE TITLE
run-fire runs one extra time step

### ISSUE THREAD

**Issue by Oliver-BE** [Oliver-BE/ring-of-fire#1]
run-fire always updates-cells 1 more time than it needs to

**Comment by icaruso21** [comment]
I think the > needs to be a >=, because it is 0 indexed.

https://github.com/Oliver-BE/ring-of-fire/blob/3827fbd0b1593eaa81598f2a04388fbf52d30e96/src/ring_of_fire/core.clj#L470-L473
