### ISSUE TITLE
Cut down on number of instructions

### ISSUE THREAD

**Issue by Oliver-BE** [Oliver-BE/ring-of-fire#11]
We need to look at our instructions to make sure all of them make sense and perhaps remove some that logically would not affect fire spread. Specifically, we should look at the weather data and decide whether or not each column has relevant data (if there is data that doesn't change much across 24 hours then we shouldn't waste time by having it be an instruction). In short, we should cut down on the number of weather variables we are looking at, if possible.

We should also consider consolidating weather variables into more useful data points such as wind direction that our program could then use in lieu of many different weather variables and having to figure it out itself.

**Comment by icaruso21** [comment]
https://cell2fire.readthedocs.io/en/latest/rstfiles/Editing.html#

**Comment by icaruso21** [comment]
<img width="337" alt="prom" src="https://user-images.githubusercontent.com/44649197/80790769-b4d07080-8b5d-11ea-9e18-7a92a8f085c8.PNG">

**Comment by icaruso21** [comment]
http://firegrowthmodel.ca/prometheus/downloads/Prometheus_Information_Report_NOR-X-417_2010.pdf
