### ISSUE TITLE
Error during evolution

### ISSUE THREAD

**Issue by icaruso21** [Oliver-BE/ring-of-fire#5]
Could the pmap mean that sometimes the second vector item gets returned before the first, causing an issue? 
<img width="864" alt="Capture" src="https://user-images.githubusercontent.com/44649197/80450235-10e18d80-88ef-11ea-92d3-56311b78fa82.PNG">

**Comment by Oliver-BE** [comment]
this error looks like lexicase selection is perhaps not working the way you thought it was? Do we need to make sure the fires are all the same size for it to work properly and not throw this error (instead of randomly selecting fires)?

**Comment by icaruso21** [comment]
Duplicate of #7
